<?php
// module/Album/view/album/album/add.phtml:

$title = 'Commande';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('commande', array('action' => 'add')));
$form->prepare();


echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nom'));
echo '</br>';
echo $this->formRow($form->get('prix'));
echo '</br>';
echo $this->formHidden($form->get('etat'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();