<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

 $title = 'Présentation';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     Ce site vous permet de passer une commande en ligne afin de ne pas perdre votre temps. <br>
     Vous restez tranquilement chez vous pendant la préparation, vos frites sont prêtes lorsque vous arrivez ! <br>
 </p>
 <p>
     Bon appetit !<br>
 </p>
 <p>
     <a href="<?php echo $this->url('commande', array('action'=>'add'));?>">Nouvelle Commande</a>
 </p>

 
 
